#!/usr/bin/env python
"""Test that AIService is being called for anomalies."""

import requests
import json
import time

def test_recommendation_flow():
    """Test that anomalies have recommendations generated by AIService."""
    
    time.sleep(1)
    
    kpis_to_test = ['AVIA_ACTIVE', 'PAYMENT_TRACE']
    
    for kpi in kpis_to_test:
        print("\n" + "=" * 70)
        print(f"Testing KPI: {kpi}")
        print("=" * 70)
        
        # Detect anomalies
        response = requests.post(
            f'http://127.0.0.1:8000/api/anomalies/detect/{kpi}', 
            params={'year': 2024}
        )
        
        if response.status_code != 200:
            print(f"✗ Failed to detect: {response.status_code}")
            continue
        
        anomalies = response.json()
        if not anomalies:
            print(f"✗ No anomalies found for {kpi}")
            continue
        
        print(f"✓ Found {len(anomalies)} anomalies")
        
        # Test each anomaly
        for idx, anomaly in enumerate(anomalies[:2], 1):  # Test first 2
            anomaly_id = anomaly['id']
            severity = anomaly.get('severity', 'N/A')
            desc = anomaly.get('description', '')[:50]
            
            print(f"\n  [{idx}] Anomaly #{anomaly_id} (severity={severity})")
            
            # Try to get recommendation
            rec_response = requests.get(
                f'http://127.0.0.1:8000/api/anomalies/{anomaly_id}/recommendation'
            )
            
            if rec_response.status_code == 200:
                rec = rec_response.json()
                print(f"      ✓ RECOMMENDATION FOUND!")
                data = rec.get('data', {})
                if data:
                    print(f"      Title: {data.get('title', 'N/A')[:60]}")
                    print(f"      Priority: {data.get('priority', 'N/A')}")
            elif rec_response.status_code == 404:
                print(f"      ✗ 404: No recommendation (AIService may not have been called)")
            else:
                print(f"      ✗ Error {rec_response.status_code}")

if __name__ == '__main__':
    test_recommendation_flow()
